name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: knowledgefactorydev.azurecr.io
           username: KnowledgefactoryDev
           password: /4jxuxihtIRjERWAme2KQEywFLtECz=7
      - run: |
          docker build . -t knowledgefactorydev.azurecr.io/knowledgefactory:${{ github.sha }}
          docker push knowledgefactorydev.azurecr.io/knowledgefactory:${{ github.sha }}
